version: "3.8"
services:
  web:
      image: nginx
      ports:
        - "8082:80"
      volumes:
        - ./index.html:/usr/share/nginx/html/index.html
      depends_on:
        - redis
      networks:
        - logflow-net
        
  
  redis:
      image: redis

networks:
  logflow-net:
    driver: bridge


  